# Generated by Django 2.0.2 on 2018-02-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.ImageField(upload_to='', verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(max_length=250, upload_to='', verbose_name='path')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('position', models.IntegerField(choices=[(0, 'Wide'), (1, 'Narrow')], verbose_name='position')),
                ('weight', models.IntegerField(choices=[(0, 'Wide'), (1, 'Narrow')], verbose_name='weight')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('general_desc', models.TextField(verbose_name='general description')),
                ('location_desc', models.TextField(verbose_name='location description')),
                ('interior_desc', models.TextField(verbose_name='interior description')),
                ('exterior_desc', models.TextField(verbose_name='exterior description')),
                ('google_place_id', models.CharField(max_length=250, verbose_name='google location')),
                ('call2action', models.CharField(max_length=250, verbose_name='call to action')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('surface', models.IntegerField(verbose_name='surface')),
                ('bedrooms', models.IntegerField(verbose_name='bedrooms')),
                ('bathrooms', models.IntegerField(verbose_name='bathrooms')),
                ('comment', models.TextField(verbose_name='comment')),
                ('status', models.IntegerField(choices=[(0, 'OPTIONS'), (1, 'ARCHIVED'), (2, 'RENTED'), (3, 'SOLD'), (4, 'RENTING'), (6, 'FUTURE')], verbose_name='status')),
                ('promoted', models.BooleanField(default=False, verbose_name='promoted')),
                ('promote_weight', models.IntegerField(verbose_name='promote weight')),
                ('slider', models.BooleanField(default=False, verbose_name='slider')),
                ('slider_weight', models.IntegerField(verbose_name='slider weight')),
                ('categories', models.ManyToManyField(related_name='categories', to='core.Feature', verbose_name='categories')),
                ('features', models.ManyToManyField(to='core.Feature', verbose_name='features')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
